server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

coingecko:
  api-url: https://api.coingecko.com/api/v3
  coins: bitcoin,ethereum
  api-key: ${COINGECKO_API_KEY}
